import styles from '../styles/Home.module.css'

import Head from 'next/head'

import { server } from '../config'
import { ReactElement } from 'react'
import { DefaultLayout } from '../components/layouts'

import type { LayoutPage } from '../types'

const getServerSideProps = async () => {
  const data = await (await fetch(server + '/api/hello')).json()
  return {
    props: {
      data,
      title: 'Home Page',
    },
  }
}

type HomeProps = {
  title: string
  data: any
}
const Home: LayoutPage<HomeProps> = ({ title, data }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {title}

      {JSON.stringify(data)}

      <main className={styles.main}>
        <h1 className="text-3xl font-bold underline bg-red-500">
          Hello world!
        </h1>
      </main>
    </div>
  )
}

Home.getLayout = (page: ReactElement) => {
  return <DefaultLayout>{page}</DefaultLayout>
}

export { getServerSideProps }
export default Home
